apiVersion: apps/v1
kind: Deployment
metadata:
  name: emotion-detection
  namespace: default
  labels:
    app: emotion-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emotion-detection
  template:
    metadata:
      labels:
        app: emotion-detection
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - name: emotion-detetcion
          image: preethu25/emotiondetection:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 51820
          livenessProbe:
            httpGet:
              path: /health
              port: 51820
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 51820
            initialDelaySeconds: 20
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emotion-detection
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: emotion-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 51820
